# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Pirate cli build - MacOS


on:
  push:
    branches:
    - master
    - beta


jobs:

  osx-build:
    name: OSX Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps (macOS)
        run: |
          brew update
          brew upgrade || true
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install gcc@8
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3
          brew install gmp

      - name: Build (macOS)
        run: |
          ./zcutil/build-mac.sh -j4
          zip --junk-paths pirate-osx src/pirated src/pirate-cli
      - name: Upload pirate-osx.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pirate-osx
          path: ./pirate-osx.zip
